# Generated by Django 4.2.5 on 2023-09-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamemode', models.CharField(choices=[('Survival', 'survival'), ('Creative', 'creative'), ('Adventure', 'adventure')], default='Survival', max_length=15)),
                ('difficulty', models.CharField(choices=[('Peaceful', 'peaceful'), ('Easy', 'easy'), ('Normal', 'normal'), ('Hard', 'hard')], default='Easy', max_length=10)),
                ('max_players', models.IntegerField(default=20)),
                ('white_list', models.CharField(choices=[('True', 'true'), ('False', 'false')], default='False', max_length=5)),
                ('view_distance', models.IntegerField(default=10)),
                ('simulation_distance', models.IntegerField(default=10)),
                ('motd', models.CharField(blank=True, default='A Minecraft Server', max_length=59)),
                ('hardcore', models.CharField(choices=[('True', 'true'), ('False', 'false')], default='False', max_length=5)),
                ('online_mode', models.CharField(choices=[('True', 'true'), ('False', 'false')], default='True', max_length=5)),
                ('pvp', models.CharField(choices=[('True', 'true'), ('False', 'false')], default='True', max_length=5)),
                ('enable_command_block', models.CharField(choices=[('True', 'true'), ('False', 'false')], default='False', max_length=5)),
                ('generator_settings', models.CharField(default='{}', max_length=300)),
                ('enforce_secure_profile', models.CharField(choices=[('True', 'true'), ('False', 'false')], default='True', max_length=5)),
                ('generate_structures', models.CharField(choices=[('True', 'true'), ('False', 'false')], default='True', max_length=5)),
                ('max_chained_neighbour_updates', models.IntegerField(default=1000000)),
                ('allow_nether', models.CharField(choices=[('True', 'true'), ('False', 'false')], default='True', max_length=5)),
                ('op_permission_level', models.CharField(choices=[('0-All permissions', '0'), ('1-Moderator', '1'), ('2-Game Master', '2'), ('3-Admin', '3'), ('4-Owner', '4')], default='4-Owner', max_length=20)),
                ('player_idle_timeout', models.IntegerField(default=0)),
                ('spawn_npcs', models.CharField(choices=[('True', 'true'), ('False', 'false')], default='True', max_length=5)),
                ('spawn_animals', models.CharField(choices=[('True', 'true'), ('False', 'false')], default='True', max_length=5)),
                ('spawn_monsters', models.CharField(choices=[('True', 'true'), ('False', 'false')], default='True', max_length=5)),
                ('spawn_protection', models.IntegerField(default=16)),
                ('max_world_size', models.CharField(default='29999984', max_length=30)),
            ],
        ),
    ]
