# Generated by Django 4.2.5 on 2023-09-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverproperties',
            name='level_seed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serverproperties',
            name='level_type',
            field=models.CharField(default='minecraft\\\\:normal', max_length=30),
        ),
    ]
