# Generated by Django 4.2.5 on 2023-09-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_serverproperties_allow_nether_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverproperties',
            name='op_permission_level',
            field=models.CharField(choices=[('0', '0-All permissions'), ('1', '1-Moderator'), ('2', '2-Game Master'), ('3', '3-Admin'), ('4', '4-Owner')], default='4', max_length=20),
        ),
    ]
