# Generated by Django 4.2.5 on 2023-09-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_serverproperties_op_permission_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverproperties',
            name='allow_nether',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=5),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='difficulty',
            field=models.CharField(choices=[('peaceful', 'Peaceful'), ('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='enable_command_block',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=5),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='enforce_secure_profile',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=5),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='gamemode',
            field=models.CharField(choices=[('survival', 'Survival'), ('creative', 'Creative'), ('adventure', 'Adventure')], default='survival', max_length=15),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='generate_structures',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=5),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='hardcore',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=5),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='online_mode',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=5),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='op_permission_level',
            field=models.CharField(choices=[('0', '0-All permissions'), ('1', '1-Moderator'), ('2', '2-Game Master'), ('3', '3-Admin'), ('4', '4-Owner')], default='4', max_length=20),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='pvp',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=5),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='spawn_animals',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=5),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='spawn_monsters',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=5),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='spawn_npcs',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=5),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='white_list',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=5),
        ),
    ]
